/*
 *
 * DiagnoseList constants
 *
 */

export const DIAGNOSE_LIST_REQUEST = 'DIAGNOSE_LIST_REQUEST';
export const DIAGNOSE_LIST = 'DIAGNOSE_LIST';
export const DIAGNOSE_LIST_SUCCESS = 'DIAGNOSE_LIST_SUCCESS';
export const DIAGNOSE_LIST_ERROR = 'DIAGNOSE_LIST_ERROR'
export const ADD_DIAGNOSE_LIST_REQUEST = 'ADD_DIAGNOSE_LIST_REQUEST'
